theme: jekyll-theme-minimal
title: Jonathan Airey
description: Software Engineer
logo: assets/profile.jpg
favicon: assets/favicon.ico
google_analytics: UA-129537452-1
repository: jonairey/jonairey.github.io
